export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_SIGNUP_SUCCESS = "SET_SIGNUP_SUCCESS";
export const SET_VIDEO_SUCCESS = "SET_VIDEO_SUCCESS";
export const SET_VIDEO_UPLOAD_SUCCESS = "SET_VIDEO_UPLOAD_SUCCESS";
